### ISSUE TITLE
Does not work on Servers

### ISSUE THREAD

**Issue by kevpears** [Adirelle/AdiCrafter#1]
Hello,

I had attempted to use this on my server, upon loading however, it ended up crashing. Below is a copy of t he crash report for your review.

`[13:04:23] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[13:04:23] [ForkJoinPool-1-worker-3/WARN]: The mod "libcd" contains invalid entries in its mod json:
- Unsupported root entry "licence" at line 9 column 12
[13:04:23] [main/WARN]: Warnings were found!
 - Mod 'Beenfo' (beenfo) 1.18.1-fabric0.45.0-1.3.3 recommends any version of modmenu, which is disabled for this environment (client/server only)!
	 - You should install any version of modmenu for the optimal experience.
 - Mod 'BetterLeads' (betterleads) 1.0.1+1.18.1 recommends version 2.0.0-beta.7 or later of modmenu, which is disabled for this environment (client/server only)!
	 - You should install version 2.0.0-beta.7 or later of modmenu for the optimal experience.
 - Mod 'Fabric Rendering Fluids (v1)' (fabric-rendering-fluids-v1) 0.1.18+3ac43d9565 recommends any version of fabric-textures-v0, which is disabled for this environment (client/server only)!
	 - You should install any version of fabric-textures-v0 for the optimal experience.
[13:04:23] [main/INFO]: Loading 108 mods:
	- adicrafter 0.3.0+mc1.18.1
	- adorn 3.1.0+1.18.1
	- adventurez 1.4.7
	- ae2 10.0.0-beta.5
	- allarrowsinfinityfix 1.0.0
	- allstackable 1.5.1-1.18.1
	- animal_feeding_trough 1.0.2+1.18
	- architectury 3.4.9
	- beenfo 1.18.1-fabric0.45.0-1.3.3
	- betterleads 1.0.1+1.18.1
	- blue_endless_jankson 1.2.1 via jankson
	- boatcontainer 1.0.4
	- book_of_the_day 1.1.0
	- buildinggadgets 1.0.10
	- cardinal-components-base 4.0.0 via buildinggadgets
	- cardinal-components-item 4.0.0 via buildinggadgets
	- cardinal-components-level 4.0.0 via buildinggadgets
	- cardinal-components-world 4.0.0 via buildinggadgets
	- ccoords 0.2.2152
	- chunky 1.2.164
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- collective-fabric 3.14
	- crowdin-translate 1.4+1.18 via beenfo
	- disenchanter 0.1.4+1.18
	- dungeons_arise 2.1.49c-fabric
	- expanded_armor_enchanting 1.0.2
	- expanded_axe_enchanting 1.0.3
	- expanded_weapon_enchanting 1.0.2
	- expandedstorage 7.3.4
	- experiencebottler 1.18.1+build.1
	- fabric 0.45.2+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.9+a1d9bbf565 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.8+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-no-mob-grief 1.1.0
	- fabric-object-builder-api-v1 1.11.1+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.9+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-registry-sync-v0 0.9.0+befed49e65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.5+fb3b57b465 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- fallingtree 3.2.0b1
	- fiber 0.23.0-2 via collective-fabric
	- guild 0.3.8
	- harvest_scythes 2.4.0
	- imm_ptl_core 1.1.8 via immersive_portals
	- immersive_portals 1.1.8
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.2.0+1.18 via adicrafter
	- libninepatch 1.1.0 via libgui
	- minecraft 1.18.1
	- mm 2.3 via harvest_scythes
	- mo_glass 1.6.1-MC1.18.1
	- mostructures 1.3.0-pre1+1.18
	- nametagtweaks-fabric 1.7
	- ninjaphenix_container_lib 1.2.10
	- omega-config 1.0.8 via mostructures
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- pipette 1.0.1
	- q_misc_util 1.1.8 via immersive_portals
	- ring_of_growth 1.2.18
	- roughlyenoughitems 7.1.361
	- silkspawners 1.1.0
	- skyvillages 1.0.1-1.18.1-fabric
	- smithingupgrades 1.5.1
	- stoneholm 1.4.1
	- tawct 1.4.2+1.18
	- team_reborn_energy 2.0.0-beta1 via ae2
	- vanillashears 1.18.1-0.1.0
	- waystones 2.4.0
	- xaerominimap 21.23.0
[13:04:23] [main/WARN]: Mod `dungeons_arise` (2.1.49c-fabric) does not respect SemVer - comparison support is limited.
[13:04:23] [main/WARN]: Mod `fallingtree` (3.2.0b1) does not respect SemVer - comparison support is limited.
[13:04:23] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/booda/Desktop/Fabric%20Mods/TestServer/libraries/net/fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=SERVER
[13:04:23] [main/INFO]: Compatibility level set to JAVA_17
[13:04:23] [main/WARN]: Reference map 'adicrafter-refmap.json' for adicrafter.mixins.json could not be read. If this is a development environment you can ignore this message
[13:04:23] [main/WARN]: Reference map 'structure-tools-refmap.json' for buildinggadgets.mixins.json could not be read. If this is a development environment you can ignore this message
[13:04:23] [main/WARN]: Reference map 'RingOfGrowth-Fabric-1.18.1-refmap.json' for ring_of_growth.mixins.json could not be read. If this is a development environment you can ignore this message
[13:04:28] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zkm000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[13:04:32] [main/INFO]: [All Stackable] Start loading!
[13:04:32] [main/INFO]: [All Stackable] Command registered.
[13:04:32] [main/INFO]: [Animal Feeding Trough] Load Complete! Enjoy :D
[13:04:32] [main/INFO]: [BetterLeads/INFO] its alive
[13:04:32] [main/INFO]: [BetterLeads/INFO] Config loaded
[13:04:33] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 3.14.
[13:04:33] [main/INFO]: Immersive Portals Mod Initializing
[13:04:33] [main/INFO]: Dimensional Threading is not present
[13:04:33] [main/INFO]: Pehkui is not present
[13:04:33] [main/INFO]: Gravity Changer is not present
[13:04:33] [main/INFO]: Definitely not up to no good
[13:04:33] [main/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIPlugin
[13:04:33] [main/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIPlugin
[13:04:33] [main/INFO]: Registered plugin provider DefaultPlugin [roughlyenoughitems] for REIServerPlugin
[13:04:33] [main/INFO]: Registered plugin provider DefaultRuntimePlugin [roughlyenoughitems] for REIServerPlugin
[13:04:33] [main/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIServerPlugin
[13:04:33] [main/INFO]: Registered plugin provider FabricFluidAPISupportPlugin for REIPlugin
[13:04:34] [main/INFO]: [STDOUT]: smithingupgrades: Loading
[13:04:34] [main/INFO]: [Fabric-Waystones] is initializing.
[13:04:34] [main/INFO]: [Fabric-Waystones] has successfully been initialized.
[13:04:34] [main/INFO]: [Fabric-Waystones] If you have any issues or questions, feel free to join our Discord: https://discord.gg/vMjzgS4.
[13:04:34] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'adicrafter'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.12.12.jar:?]
	at net.minecraft.server.Main.main(Main.java:106) [server-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.12.12.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.12.12.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at dev.adirelle.adicrafter.crafter.CrafterFeature.<clinit>(CrafterFeature.kt:25) ~[adicrafter-0.3.0+mc1.18.1.jar:?]
	at dev.adirelle.adicrafter.AdiCrafter.onInitialize(AdiCrafter.kt:9) ~[adicrafter-0.3.0+mc1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
	... 15 more
Caused by: java.lang.RuntimeException: Cannot load class dev.adirelle.adicrafter.crafter.CrafterScreen in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:282) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:240) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.12.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at dev.adirelle.adicrafter.crafter.CrafterFeature$SCREEN$1.<init>(CrafterFeature.kt) ~[adicrafter-0.3.0+mc1.18.1.jar:?]
	at dev.adirelle.adicrafter.crafter.CrafterFeature$SCREEN$1.<clinit>(CrafterFeature.kt) ~[adicrafter-0.3.0+mc1.18.1.jar:?]
	at dev.adirelle.adicrafter.crafter.CrafterFeature.<clinit>(CrafterFeature.kt:25) ~[adicrafter-0.3.0+mc1.18.1.jar:?]
	at dev.adirelle.adicrafter.AdiCrafter.onInitialize(AdiCrafter.kt:9) ~[adicrafter-0.3.0+mc1.18.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.12.12.jar:?]
	... 15 more
`

**Comment by Adirelle** [comment]
Should be fixed by 1d415cb44305c9d4df61f88c24c739a07faa83a8.
